#+BABEL: :tangle no :cache no :session yes :results silent :no-expand yes :noweb yes :exports code :padline yes
SEXML

s-expressions for xml is an extensible library which provides a sugar-sweet s-expression syntax for spitting out xml documents.  its initial use is as a converter for a given DTD. it creates a package which exports a function for each ELEMENT (that's an xml tag) in the DTD and translates each of the attributes in the ATTLIST of the ELEMENT into a lispy keyword.  this allows us to use a nice syntax for creating xml documents, based on the DTD to support.  aside from this, the system will become extensible through ContextL.

SEXML currently doesn't aim to use everything we can distil from the DTD, it aims to get just enough information so we can easily generate the XML documents.  there's currently NO checking as to whether or not the generated document will be a valid DTD.  aside from that the library is mainly built in order to support web-standards like html and svg.  if there are any non-XML oddities which should to be supported, they likely aren't supported by default.

* administration
contains all sorts of administrative work.

** asdf system
trivial package for an open source library.  uses cl-ppcre.

#+begin_src lisp :tangle sexml.asd
  (asdf:defsystem :sexml
    :name "S-Expressions for XML generation"
    :author "Aad Versteden <madnificent@gmail.com>"
    :version "0.0.1"
    :maintainer "Aad Versteden <madnificent@gmail.com>"
    :licence "MIT"
    :description "s-expressions for xml is a library which provides a sugar-sweet s-expression syntax for spitting out xml documents based on a DTD"
    :depends-on (cl-ppcre alexandria cxml contextl)
    :serial t
    :components ((:file "packages")
                 (:file "sexml")))
#+end_src

** packages
sexml may generate new packages for the DTD's which it imports, however it will only use a single predefined package.

#+begin_src lisp :tangle packages.lisp
  (defpackage :sexml
    (:use :cl-ppcre :alexandria :contextl-common-lisp)
    (:export :support-dtd :with-compiletime-active-layers :standard-sexml))
#+end_src

* sexml code structure
sexml provides a simple way to create a new package from a given DTD.  we've split the handling of that function in a few chapters.  it boils down to the following:
- support for creating, populating and exporting symbols in packages
- support for distilling the correct lisp-name from an external name
- support for distilling information from a DTD
- support for customization by virtue of ContextL
- stiching it all together for a final realization

the following code-snippet describes how everything is in fact connected together.

#+begin_src lisp :tangle sexml.lisp
  (in-package :sexml)
  
  <<managing-symbols>>
  
  <<lisp-naming>>
  
  <<dtd-information>>
  
  <<hooking-everything-together>>

  <<customization-support>>

#+end_src

* customization support
:PROPERTIES:
:noweb-ref: customization-support
:END:
in order to provide extensions and changes to the base system, we use ContextL.  we enable contextl at compiletime, so that the wanted code for each of teh tags can be generated.  this expansions allow us to provide and combine the functionality the user wants at compiletime.  

** enabling layers at compiletime
because the layers are expanded at compiletime, we need to ensure ContextL has access to them at compiletime.  macroexpansions always occur in the current environment.  however, to ensure that the functions which each nested macro-expansion call can make use of the activated layer, we need to ensure that the environment holds, for the whole time of the expansion/compilation.  we can force this by use of eval.

#+begin_src lisp
  
  (defmacro with-compiletime-active-layers ((&rest layers) &body body)
    (let ((layers-to-activate (loop for layer in layers
                                 unless (contextl:layer-active-p layer)
                                 collect layer)))
      (mapcar #'contextl:ensure-active-layer layers-to-activate)
      (dolist (bd body)
        (eval bd))
      (mapcar #'contextl:ensure-inactive-layer layers-to-activate)
      nil))
  
#+end_src

** base sexml system
the base sexml system creates one function for each of the elements in the XML output. keywords are used to supply the values of their attributes.  once a non key-value pair is given, all other elements are printed as if they were inside the content of the tags.

*** creating function symbols
the most important task is exposing the function's symbols.  this is done in the <sexml-functions> layer.

a function is built which knows each of the possible attributes.  the function is compiled in an environment which contains a property list with as key the keyword which the function has, and as value a string representing the attribute which should be printed.  it only has an &rest argument, as it accepts anything that's given to it and discovers what are key-value pairs and what is resting content.  the resulting forms are pushed to the list of methods needed to support this element.

#+begin_src lisp
  (deflayer sexml-functions ())
    
  (define-layered-method entity-definition-forms
    :in-layer sexml-functions
    :around (entity package)
    (let ((sexp-entity (function-symbol entity package))
          (sexp-attributes (mapcar (rcurry #'argument-symbol :keyword)
                                   (attributes entity))))
      `((let* ((key-translations ',(loop for key in sexp-attributes
                                      for expansion in (attributes entity)
                                      append (list key (name expansion)))))
          (defun ,sexp-entity (&rest args)
            (let* ((keys ,(if (null (subelements-p entity))
                              `(loop for (a b) on args by #'cddr
                                  append (list (getf key-translations a) b))
                              `(progn (loop while (keywordp (first args))
                                     append (list (getf key-translations (pop args))
                                                  (pop args)))))))
              (format nil ,(concatenate 'string
                                        "<" (name entity) "两誉ㄩ篚忮戾礤铘蟓孱糸豉⒕劲换翎麒孱篚忮戾礤铘蟓孱糸豉窿换泔铘孱麒孱篚忮戾礤铘蟓孱糸豉ㄣ镱汜翦钺翦篝蜷铉⒓钺礤孱糸豉⒕┅括殒铛祆篚忮戾礤铘蟓孱糸豉┅扉篝щ妁螬扉篝щ妁п蜱螬┅┅括汜祆铄舡礤翳镤┅┅＋孱溥篁屮痫螋轭骢钽糸镱簌礅镬轸轶栳钿殒翳骢钽糸镱麒殂汜忮躞邃骘泸遽糸铉盱狎屮痫螋邃翳轶灬弪栳钿戾筢殇屮痫螋轭绠镱禊翳簌礅镬镦翳骢钽糸镱铄邃麸忮屮痫螋邃＋忮玳钸篁扉箴ㄤ彐灬弪屮痫螋骢钽糸镱簌礅镬īㄤ彐轭瀛灬弪邃礤翳镤孱糸豉溴骈铋糸镱骘蝽洪瞽灬弪屮痫螋骢钽糸镱簌礅镬横蝻躅ㄥ铘轸疳汶徵濠戾è簌礅镬ㄦ躅泗轱瞽簌礅镬孱糸豉疳汶徵濠┅啜ㄥ痫螋聃雉簌礅镬簌礅镬疳汶徵聃雉簌礅镬┅括汜祆铄舡礤翳镤┅┅＋孱溥篁忮趑弪篦犷蝈痫螋轭翳骢钽糸镱麒殂麇沲蝌孱綮躞镱禊腩秣翳蝈篝狎珲礤铘翳箴邈骘蜚弩骢钽糸镱麒殂怙翳栳鲥犷蝈篝犷脲麸栳鲥犷弼孱铛礅弪镦狎珲礤铘轭翳蝈篝狎珲礤铘翳轶轶铒驽狍殁戾轭秕箫祯糸镱狍麇汜篚痧禊犷铛礅弪镦狎珲礤铘螽麇篦犷轶祜徜邃麇鏖祆篝殪麽铘麸珏翳泔溴栝铘轭麇蝈躞邃麸翳轶灬弪徜潴泔溴栝铘蟋怡秭弪蜷溟铉篦犷牒狎珈轶舡溟箴狒汨骘翳骢钽糸镱麒殂麇篚痧矧舢＋忮玳钸篁扉箴ㄤ彐灬弪篦犷氕箦盱滹沲礤铘邃狒趄殁豸弩īㄤ彐轭瀛灬弪邃礤翳镤孱糸豉溴骈铋糸镱骘蝽洪瞽灬弪篦犷氕箦盱滹沲礤铘邃狒趄殁豸弩横蝻躅ㄥ铘轸疳汶徵濠戾舄è簌礅镬ㄦ躅泗轱瞽簌礅镬孱糸豉疳汶徵濠ㄡ趑蜷怩翦簌礅镬磲疸狎蜚躜蝙＇狎珲礤铘簌礅镬ㄣ狎疳汶徵濠ㄡ趑蜷怩翦孱糸豉┅ㄡ趑蜷怩翦脲黠蜾磲疸狎蜚躜蝙＇狎珲礤铘簌礅镬弘妁黠蜾ㄡ趑蜷怩翦孱糸豉┅┅啜ㄤ彐礤翳镤篦犷牒狎珈轶舡溟箴狒汨横蝻躅è簌礅镬ㄥ耢К簌礅镬┅狎珈轶舂戾è狎珈轶ㄣ犰飙铄舡礤翳镤┅箦翩篦犷牒横蜱扉篝脲黠蜾狎珞狎珈轶舂祜镳骘狒趄簌轭Ж泪趑蜷怩翦簌礅镬螬骘狒趄脲轭Ж泪趑蜷怩翦脲黠蜾螬泔祆邈篦犷牒喉犭瀛脲黠蜾狎狒趄脲狒趄簌铋飑┅箦翩篦犷牒横蜱扉篝蝈篝狎珈轶舂蝈篝箦翩篦犷牒横蜱扉篝脲狎珈轶舂舂狎珈轶舂括汜祆铄舡礤翳镤┅┅＋孱溥篁箝眇戾躞麇箝眇扉纟翳躞镦箦盱篝犷溽蜾盱铒翎糸镱怡篚痧禊轭灬弪麒殂屮翦钿泔铘衢铙翳翳蝈痱弼轱躞灬弪螽翳轶磲脲轸遽箝弪麸瘐忪轶篚痧矧骘脑漠＋忮玳钸篁扉箴ㄤ彐灬弪篝犷溽蜾箦盱ㄥ痫螋骢钽糸镱簌礅镬＋篦犷篦犷氕箦盱滹沲礤铘邃狒趄殁豸弩箦盱骢钽糸镱螬＋孱溥篁栾镫轭轸犰麸珏翳弪盒蚁信以膳雍侯秣邂蝈婧栾镫轭绛弼弪翳轭绛麸珏翳弪号文翳轶汨狃翦溴筱蜷忮栾弼弪翳轭轶泔铑邈翦麸珏翳弪戾鲥蜥玳铉骝镯遽汨镦翳躞邃扉怛狎殄螽翳骈蝮翳轭翳扉怛狎鏖祆滹轶泸遽翦犷镡赍泗麸磲钺珏犰镦翳轭骘蝽狒轱轭翳脑漠铄躔轶泸遽糸铉蝈驽蝈钽麸铄疳汶徵麒殂鏖祆篝矧遽汨镦翳骢钽糸镱螽骘遽汨镦翳屐屙孱趔轭翳脑麇ъ泸遽翦铄骢钽糸镱骘遽汨镦翳骢钽糸镱麇ъ泸遽翦翳狎珲礤铘扉篝骝镯翳狎珲礤铘扉篝趄轹獒轫痨屙孱翎糸镱轶躞邃麒殂箬秕熹黠螂骘盹篝翎珞麇蝈玳篝弪遽汨镦翳骢钽糸镱轭翳玳鲥疳汶徵犷屮痫螋翳屙＋忮玳钸篁扉箴ㄤ彐轭瀛灬弪邃骢钽糸镱孱糸豉溴骈铋糸镱骘蝽ㄥ铘轸疳汶徵濠ê滹沲礤铘狒轱㈠铘轸溴骈铋糸镱骘蝽轶汜祆邃鏖翳犷孱糸豉犷疳汶徵镡赍泗ㄢ雉溴骈铄轭箦盱┊轸箬秕熹蝈趱蝾犰骘蝽铄邃邃麸珏铄蜥翦翳骢钽糸镱螽ê礤翳镤ㄥ铘轸疳汶徵濠ㄤ邈灬蝈ㄩ珙矧孱糸豉疳汶徵濠铋飑ㄤ彐磲泸篚痧矧舡漪ㄦ殪疳汶徵孱犴濠戾è漪黼漪洵镡赍泗骈戾┅疳汶徵黼疳汶徵瀛镡赍泗疳汶徵孱犴濠┅啜痱镧括祜镳骘屐屙孱轭ㄤ翡屐屙孱趔漪洎泔祆邈啜痱镧括孱糸豉溴骈铋糸镱骘蝽屐屙孱疳汶徵濠┅┅＋孱溥篁磲钺玳铉簌礅镬盒蚁信以膳雍侯秣邂蝈婧磲钺玳铉簌礅镬号文簌礅镬磲钺珏礤铘怙殪滹黝麸泸遽糸铉疳汶徵麒孱蝈聃弩翦犷痱秭殇轭麽麸泸遽翦疳汶徵溴骈铋糸镱箫翳疳汶徵轶溴骈铄轭麽遽箝弪镱翳妁弩麇汜蝈痱弩孱疳汶徵怡翳疳汶徵轸箦戽狍骈蝮狎珲礤铘犷翳扉篝镦簌礅镬麒殂鏖祆铄邃麸忮屮痫螋邃灬翦虍鏖翳翳狒轭黹钿麇轫痨屙孱翳赭骢钽糸镱麒殂狎躞邃轭翳磲轭忪镢氘＋忮玳钸篁扉箴ㄤ彐躅黼疳汶徵瀛镡赍泗钺礤泸遽翦铄疳汶徵镡赍泗扉篝矧ㄦ轭洵疳汶徵钺礤磲脲疳汶徵钺礤┅┅ㄤ彐躅疳汶徵瀛屮痫螋蟓簌礅镬疳汶徵簌礅镬㈨犭弩篚蝈疳汶徵腩秣轸铄邃麸屮痫螋簌礅镬犷屮痫螋轸ㄥ痫螋簌礅镬ㄦ轵篝疳汶徵濠箦翩ㄣ潋灬篝疳汶徵濠ㄣ镱簌礅镬铋飑簌礅镬ㄤ彐躅疳汶徵瀛溴沆狎狒轱疳汶徵濠泸遽翦溴骈铋糸镱骘翳疳汶徵澧戾è疳汶徵ㄦ轵篝疳汶徵濠ㄥ痫螋蝈篝疳汶徵濠┅啜溴骛徙脶珏疳汶徵瀛钺礤疳汶徵濠ê屮痫螋厘痫螋螬┅＋孱溥篁扉箴钺黹铉盒蚁信以膳雍侯秣邂蝈婧扉箴钺黹铉号文趄犷箪狒弩篝蜷铉镦屮翦蝾犰溴骈铋糸镱轭麸扉箴篝蜷铉螽鲥蝙扉趑戾轶腩秣徕秕翳屮翦蝾犰骘蝽狒怡溴驷蹯衄轸汜忮蝻蹒桁犷翳轭绠忮篝彐骘螋篝踱栳忮孱轫痨屙孱翦麒殂趄犷箪狒弩屮翦蝾犰篝蹑麸箫礤翳轭翳狒箬秕熹祜镫盹蝈矧戾篌扉脲扉箴泔溴＋忮玳钸篁扉箴ㄤ彐躅黼扉箴簌礅镬ㄥ铘轸疳汶徵濠麒孱扉篝疳汶徵濠箦翩疳汶徵ㄦ轵篝疳汶徵濠┅麒孱疳汶徵屦疳汶徵濠箦翩疳汶徵疳汶徵瀛钺礤疳汶徵濠┅箦翩孱糸豉ㄣ飙痧泸搴蝈珏蝈痨徙瀛犰④塄孱糸豉⒓┅箦翩孱糸豉ㄣ飙痧泸搴蝈珏蝈痨徙瀛犰④堠孱糸豉⒕┅箦翩孱糸豉ㄣ飙痧泸搴蝈珏蝈痨徙瀛犰孱糸豉┅箦翩孱糸豉ㄣ飙痧泸搴蝈珏蝈痨徙瀛犰⑦孱糸豉┅箦翩孱糸豉ㄣ飙痧泸搴蝈珏蝈痨徙瀛犰⒑孱糸豉┅箦翩孱糸豉ㄣ飙痧泸搴蝈珏蝈痨徙瀛犰ㄛ岘荸ㄛ镰谳孱糸豉④鼙苘并┅箦翩孱糸豉篝蜷铉躔汜箦孱糸豉┅换翳轶轶痫螋徕戾怩滹弩瞌黠螂铋沐镱盹溴蝾盹溴狍篚礤ㄩ铘弪孱糸豉ㄦ轭洵疳汶徵疳汶徵濠┅＋孱溥篁漪轭骘蝽狒轱盒蚁信以膳雍侯秣邂蝈婧漪洵轭骘蝽狒轱号文疳蝮轭翳漪轶瞌疳螋殂蹯狎禊泔眇戾怩轸轶翳盹篝泔眇戾翎箅狎秕钿麇滹瞌衢麸滹犷翳轭弩疱汩犰禊驷钽桢蝈麇躞沆痧泸麸驽翥翳蝈戾鲠铘痖邈弩镦轭骘蝽狒轱犷牾篝溟篝殪麒狒铄邃邃篝蝓泗躜镦脑翳脑泔铘衢铙翳趄邋轫痫螋犷轭骘蝽狒轹豉疱镦轭骘蝽狒轱町盘磐盼汉泔铘衢铙翳溴骈铋糸镱镦翎绠麇铄邃麸腩秣翳钺礤镦翳翎犷麒弭桢矧铒轸屙痿猎蕴捎汉翳扉篝镦狒趄殁豸弩翎徙沐痿犷麒殂鲠祯弩翳狒趄殁豸弩磲栳鲥麇铄邃翳扉篝镦狒趄殁豸弩狍篝蜷铉骘翳脲黠蜾狎珲礤铘镦翳骢钽糸镱盼陨再汉脑箴邈殒殂狒轱磲泔铘衢铆扉脲磲泸矬翳妁狎扉翦蜥翳秕玷铄篝徕戾屮疳铙轱铙麒殂汜忮躞邃蝻蹒桁犷麒弪瀹翳妁栳鲥钺礤麸屮疳钿骝镯犷篝蜷铉麸屮疳钿麸狃痱镝汨翳蝈犰泔眇戾轸轭翳脑轶屮疳钿轭翳孱糸糸弩麇ъ翎汶戾翳麒镬翳轭狍骘祆秣蠛蝈徜轭翳泔眇戾翦脑犷泔铞弪轸麸翳蝈扉篝螽镱骘翳屐屙孱趔镱骘翳狒綮轶犷镱骘翳孱糸糸弩屮疳钿犰孱糸糸弩轭翦蝾犰禊麒殂礤犷麇ъ镱禊铄邃麸滹镱疳篌秭弪翳扉篝镦孱糸弩屮疳钿翳孱糸糸弩轭翳屐屙孱犷狒綮轶箦泗轱町疳蝮翳篝蜷铉泔铘孱镦屐屙孱犷狒綮轶轭麸镡赍泗骘蝈驽蝈钽怡翳脑漠盹溴翳盹溴泔铙轶趔镦翳骘祆秣轭绾脑汉翳脑轶玳鲥蝈徜徕戾骈戾躔镱泸遽糸镱麒殂鏖祆忮疳蝮邃狒翳狒糸礤盘磐盼汉犷屐屙孱泔铘衢铙轸篝蜷铉钺礤犷扉篝镦狒趄殁豸瀛镡赍泗麒殂翳屐屙孱徙沐痿螽猎砸陕赵汉犷狒趄殁豸泔铙轶趔镦篝蜷铉钺礤沆狍溴骈铋糸镱＋忮玳钸篁扉箴ㄤ彐沆狍漪īè疳翳洪铋翎蜱吼狒候遽溴漪洵疳翳ㄥ戾礤铘蟓栳箬洪铋翩矧磲脲栳箬翎忪呼弩у聃犰横沣弩箫漪洵屐屙孱趔栳箬┅ê滹沲礤铘狒轱⒛狒狍趄蹉趱蝈麒殂泔铘衢铙犰轭骘蝽狒轱镦脑漠┅ㄤ彐沆狍屐屙孱īè钺礤洪铋翎蜱侯犴候遽溴钺礤ㄡ趑蜷怩翦洪铋翩矧铋横沣弩箫狒趄殁豸弩篚忮戾礤铘蟓洪铋翎蜱后踱屐屙孱趔洪铋翩矧铋横沣弩箫篚忮戾礤铘蟓皓┅ㄤ彐沆狍狒趄殁豸īè钺礤洪铋翎蜱侯犴候遽溴钺礤┅ê滹沲礤铘狒轱Ⅱ屦蝈箦铘痫篌殁戾狒趄殁豸骘犷屐屙孱簪┅＋孱溥篁泔蝌弩痫钿孱沐麸簌礅镬屐屙孱趔犷狒趄殁豸弩栳鲥泔蝌弩痫钿轭簌礅镬螽翳妁狎徙沐篌殁戾蝈箴邈糸鲥禊翳蝻蹒＇骢钽糸镱簌礅镬犷＇狎珲礤铘簌礅镬翳弩狎轫痨屙孱翦桢蝈＋忮玳钸篁扉箴ㄤ彐珏铄蜷骢钽糸镱簌礅镬ㄥ戾礤铘疳汶徵濠ê滹沲礤铘狒轱Ⅱ弭躜铙簌礅镬骘翳骢钽糸镱镦屐屙孱轭疳汶徵澧ê礤翳镤è屐屙孱屐屙孱舂疳汶徵濠黼扉箴簌礅镬钺礤屐屙孱舂疳汶徵濠┅ㄤ彐珏铄蜷狎珲礤铘簌礅镬ㄡ趑蜷怩翦疳汶徵濠ê滹沲礤铘狒轱Ⅱ弭躜铙簌礅镬骘翳狎珲礤铘麒殂汜忮玳鲥麸翳狒趄殁豸瀣轫痫螋邃轭疳汶徵澧ê礤翳镤è狒趄殁豸狒趄殁豸濠疳汶徵濠黼扉箴簌礅镬钺礤狒趄殁豸濠疳汶徵濠┅＋孱溥篁犰翦蜷铉翳漪徙沐篌矧礤翳镤骘徜溟铉犷骈钿轭屐屙孱趔轭翳漪＋忮玳钸篁扉箴ㄤ彐珏铄蜷漪洵屐屙孱趔ㄤ翡ê滹沲礤铘狒轱Ⅱ弭躜铙翳屐屙孱趔镦翳滹沲礤铘ê礤翳镤ㄤ翡祜镳骘鲠忮轭翳栳箬鲠祯弩镦ㄤ翡屐屙孱趔栳箬漪洎泔祆邈鲠飑┅ㄤ彐珏铄蜷徜洵屐屙孱ㄤ翡屐屙孱舂ê滹沲礤铘狒轱⑨滗煎戾礤铘麸翳漪渚ê礤翳镤è漪漪洎ㄥ戾礤铘屐屙孱舂箦翩ㄧ弭栳箬钺礤屐屙孱舂ㄤ翡屐屙孱趔栳箬漪洎屐屙孱舂┅ㄤ彐珏铄蜷骈钿屐屙孱ㄤ翡钺礤篝蜷铉ê滹沲礤铘狒轱Ⅲ遽蜚桢骘翳屐屙孱蝈痱弩孱糸铉碱犴瀛篝蜷铉轭翳漪洧ê礤翳镤è漪漪洎钺礤篝蜷铉ㄧ弭栳箬钺礤篝蜷铉ㄤ翡屐屙孱趔栳箬漪洎┅ㄤ彐珏铄蜷徜洵狒趄殁豸ㄥ戾礤铘狒趄殁豸濠ê滹沲礤铘狒轱Ⅱ彗轶翦蝮翳屮轶翦钽镦坚趑蜷怩翦骘煎戾礤铘井ê礤翳镤è屐屙孱屐屙孱舂ㄡ趑蜷怩翦狒趄殁豸濠瘐箬狒趄殁豸ㄡ趑蜷怩翦屐屙孱舂┅＋孱溥篁疳蝮轭翳脑疳蝮轭翳脑轶蝻犰疳轭轭翳狎箦翳弪彐矧麇怙忮骘蝈翳顼潴翳狒磲溴犷磲轭翎轭秘吞翳犷塍情焘弪箩蹴犷犷尼鲩涕汨翦忪狨麇犰箫腴钿禊徙沐痿翳狒轸犷烫切扉怛狎狍轸牾篝麸顼镤骘秕瘐蝠矬瀹栾镫轭轸麸珏翳弪犰翳痱弼轱躞泔铙趄蹉糸镱铄邃麸忮栾镫邃麸珏翳弪箫翳妁珏铄蜥翦铋沐犷泔眇戾翦脑默忉箦镱翳轭瘐骈戾＋忮玳钸篁扉箴ㄤ彐躅黼漪洵镡赍泗ㄦ殪濠磲脲轭篝犷沐т翡吼狒骈戾┅ㄤ彐沆狍漪洵筢栳钿戾筢轰彐狨祠栳钿戾颟è漪洪铋翎蜱轰翡候遽溴漪洎ê滹沲礤铘狒轱Ⅲ狲栳钿戾麒殂汜祆翳泔蝌邈礤翳镤镱轸脑蘑┅ㄤ彐礤翳镤筢哄戾礤铘溴沆狎狒轱è栳钿戾漪洵筢栳钿戾颟钺礤盹溴飑ㄡ滗屐屙孱ㄤ翡栳钿戾颟磲脲轭篝犷沐у戾礤铘侯犴钺礤后踱屐屙孱趔铒ㄥ盹溴哄眇豉┅┅ㄤ彐礤翳镤筢横趑蜷怩翦溴沆狎狒轱è栳钿戾漪洵筢栳钿戾颟屐屙孱舡钺礤狒趄殁豸瀛钺礤豉疱溴驷蹯舂ㄤ邈灬蝈ㄩ珙矧豉疱溴驷蹯舂ㄡ滗狒趄殁豸ㄦ轭洵屐屙孱ㄤ翡栳钿戾颟屐屙孱舡钺礤磲脲轭篝犷沐п趑蜷怩翦侯犴狒趄殁豸瀛钺礤┅ㄤ彐礤翳镤轭轸獒扉瀛轭篝犷沐横骠弪è漪漪洎脲疳翳犰祜鳝雉桢颦脲螬戾è栳钿戾磲脲轭篝犷沐т翡筢栳钿戾轰翡漪洎┅ㄣ盱吼狎箦漪洵骈戾疳翳栳钿戾颟┅＋孱溥篁